name: DoseMe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  lottie: ^2.7.0
  provider: ^6.1.1
  easy_localization: ^3.0.1
  flutter_spinkit: ^5.1.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.11
  animated_splash_screen: ^1.3.0
  flutter_local_notifications: ^17.1.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.4
  js: ^0.6.7
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/animations/pillsplash.json
    - assets/animations/Animation1.json
    - assets/images/pill_3d_rendered.png
    - assets/icon/app_icon.png
